# Generated by Django 5.0.2 on 2024-03-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_customer_cloth_description_cloth_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='image',
            field=models.ImageField(upload_to='files/cover/'),
        ),
    ]
