# Generated by Django 5.0.2 on 2024-03-13 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cloth_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='category',
            field=models.ForeignKey(choices=[('man', 'Man'), ('woman', 'Woman'), ('children', 'Children'), ('couples', 'couples')], on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
