# Generated by Django 5.0.2 on 2024-03-14 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_cloth_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='category',
            field=models.ForeignKey(choices=[('Man', 'Man'), ('Moman', 'Woman'), ('Children', 'Children'), ('Couples', 'Couples')], on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
