# Generated by Django 5.0.2 on 2024-03-18 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
