# Generated by Django 5.0.2 on 2024-03-18 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cloth',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
