# Generated by Django 5.0.2 on 2024-03-19 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_cartitem_cart_remove_cartitem_cloth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cloth')),
            ],
        ),
    ]
