# Generated by Django 5.0.2 on 2024-03-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_cart_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='category',
        ),
    ]
