# Generated by Django 5.0.2 on 2024-03-21 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_cartitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crown', models.CharField(blank=True, max_length=100)),
                ('shoulder', models.CharField(blank=True, max_length=100)),
                ('chest', models.CharField(blank=True, max_length=100)),
                ('waist', models.CharField(blank=True, max_length=100)),
                ('hips', models.CharField(blank=True, max_length=100)),
                ('inseam', models.CharField(blank=True, max_length=100)),
                ('floor', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
