# Generated by Django 5.0.2 on 2024-03-21 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
