# Generated by Django 5.0.2 on 2024-03-22 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_rename_first_name_customer_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crown', models.FloatField()),
                ('shoulder', models.FloatField()),
                ('chest', models.FloatField()),
                ('waist', models.FloatField()),
                ('hips', models.FloatField()),
                ('inseam', models.FloatField()),
                ('floor', models.FloatField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='measurement_icons/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
