# Generated by Django 5.0.2 on 2024-03-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_cartitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='chest',
            field=models.FloatField(help_text='In cm'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='crown',
            field=models.FloatField(help_text='In cm'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='floor',
            field=models.FloatField(help_text='In cm'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='hips',
            field=models.FloatField(help_text='In cm'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='inseam',
            field=models.FloatField(help_text='In cm'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='shoulder',
            field=models.FloatField(help_text='In cm'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='waist',
            field=models.FloatField(help_text='In cm'),
        ),
    ]
