# Generated by Django 5.0.2 on 2024-04-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_order_status_order_trackno_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='cloth',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
