# Generated by Django 5.0.2 on 2024-04-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout',
            field=models.BooleanField(default=False),
        ),
    ]
